// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  formDataBodySerializer,
} from '@hey-api/client-fetch';
import type {
  HealthData,
  HealthResponse,
  UploadCsvData,
  UploadCsvResponse,
  UploadCsvError,
  ListDatasetsData,
  ListDatasetsResponse,
  ListDatasetsError,
  GetDatasetData,
  GetDatasetResponse,
  GetDatasetError,
  GetEmbeddingJobData,
  GetEmbeddingJobResponse,
  GetEmbeddingJobError,
  StartEmbeddingJobData,
  StartEmbeddingJobResponse,
  StartEmbeddingJobError,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health
 * Return service liveness status.
 */
export const health = <ThrowOnError extends boolean = false>(
  options?: Options<HealthData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<HealthResponse, unknown, ThrowOnError>({
    url: '/health',
    ...options,
  });
};

/**
 * Upload Csv
 * Parse and persist an uploaded feedback CSV.
 *
 * Returns 201 with the ingestion report on success (even a partial one).
 * Returns 400 — persisting nothing — when the header lacks
 * ``feedback_text`` or when every data row was rejected.
 */
export const uploadCsv = <ThrowOnError extends boolean = false>(
  options: Options<UploadCsvData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<UploadCsvResponse, UploadCsvError, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/ingestion/uploads',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  });
};

/**
 * List Datasets
 * List datasets newest-first, paginated.
 */
export const listDatasets = <ThrowOnError extends boolean = false>(
  options?: Options<ListDatasetsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListDatasetsResponse,
    ListDatasetsError,
    ThrowOnError
  >({
    url: '/ingestion/datasets',
    ...options,
  });
};

/**
 * Get Dataset
 * Fetch one dataset and every feedback item ingested from it.
 */
export const getDataset = <ThrowOnError extends boolean = false>(
  options: Options<GetDatasetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetDatasetResponse, GetDatasetError, ThrowOnError>({
    url: '/ingestion/datasets/{dataset_id}',
    ...options,
  });
};

/**
 * Get Embedding Job
 * Fetch the latest embedding job's status for a dataset.
 */
export const getEmbeddingJob = <ThrowOnError extends boolean = false>(
  options: Options<GetEmbeddingJobData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetEmbeddingJobResponse,
    GetEmbeddingJobError,
    ThrowOnError
  >({
    url: '/ingestion/datasets/{dataset_id}/embed',
    ...options,
  });
};

/**
 * Start Embedding Job
 * Start or resume embedding every un-embedded feedback item in a dataset.
 */
export const startEmbeddingJob = <ThrowOnError extends boolean = false>(
  options: Options<StartEmbeddingJobData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    StartEmbeddingJobResponse,
    StartEmbeddingJobError,
    ThrowOnError
  >({
    url: '/ingestion/datasets/{dataset_id}/embed',
    ...options,
  });
};
