// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  formDataBodySerializer,
} from '@hey-api/client-fetch';
import type {
  HealthData,
  HealthResponse,
  LlmHealthData,
  LlmHealthResponse,
  UploadCsvData,
  UploadCsvResponse,
  UploadCsvError,
  ListDatasetsData,
  ListDatasetsResponse,
  ListDatasetsError,
  GetDatasetData,
  GetDatasetResponse,
  GetDatasetError,
  GetEmbeddingJobData,
  GetEmbeddingJobResponse,
  GetEmbeddingJobError,
  StartEmbeddingJobData,
  StartEmbeddingJobResponse,
  StartEmbeddingJobError,
  StartClusteringRunData,
  StartClusteringRunResponse,
  StartClusteringRunError,
  GetClusteringRunData,
  GetClusteringRunResponse,
  GetClusteringRunError,
  ListClustersData,
  ListClustersResponse,
  ListClustersError,
  ListClusterItemsData,
  ListClusterItemsResponse,
  ListClusterItemsError,
  GetClusterSummaryData,
  GetClusterSummaryResponse,
  GetClusterSummaryError,
  GetClusterMapData,
  GetClusterMapResponse,
  GetClusterMapError,
  PostChatMessageData,
  PostChatMessageError,
  GetConversationData,
  GetConversationResponse,
  GetConversationError,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health
 * Return service liveness status.
 */
export const health = <ThrowOnError extends boolean = false>(
  options?: Options<HealthData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<HealthResponse, unknown, ThrowOnError>({
    url: '/health',
    ...options,
  });
};

/**
 * Llm Health
 * Check Anthropic API connectivity and configuration.
 *
 * Makes a real API call to verify the key works and Claude responds.
 * This is not a real summarization — just a test message.
 *
 * Returns:
 * 200 with {"status": "ok"} if the API key is set and Claude responds.
 * 503 if API key is missing or Claude is unreachable.
 */
export const llmHealth = <ThrowOnError extends boolean = false>(
  options?: Options<LlmHealthData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<LlmHealthResponse, unknown, ThrowOnError>({
    url: '/health/llm',
    ...options,
  });
};

/**
 * Upload Csv
 * Parse and persist an uploaded feedback CSV.
 *
 * Returns 201 with the ingestion report on success (even a partial one).
 * Returns 400 — persisting nothing — when the header lacks
 * ``feedback_text`` or when every data row was rejected.
 */
export const uploadCsv = <ThrowOnError extends boolean = false>(
  options: Options<UploadCsvData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<UploadCsvResponse, UploadCsvError, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/ingestion/uploads',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  });
};

/**
 * List Datasets
 * List datasets newest-first, paginated.
 */
export const listDatasets = <ThrowOnError extends boolean = false>(
  options?: Options<ListDatasetsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListDatasetsResponse,
    ListDatasetsError,
    ThrowOnError
  >({
    url: '/ingestion/datasets',
    ...options,
  });
};

/**
 * Get Dataset
 * Fetch one dataset and every feedback item ingested from it.
 */
export const getDataset = <ThrowOnError extends boolean = false>(
  options: Options<GetDatasetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetDatasetResponse, GetDatasetError, ThrowOnError>({
    url: '/ingestion/datasets/{dataset_id}',
    ...options,
  });
};

/**
 * Get Embedding Job
 * Fetch the latest embedding job's status for a dataset.
 */
export const getEmbeddingJob = <ThrowOnError extends boolean = false>(
  options: Options<GetEmbeddingJobData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetEmbeddingJobResponse,
    GetEmbeddingJobError,
    ThrowOnError
  >({
    url: '/ingestion/datasets/{dataset_id}/embed',
    ...options,
  });
};

/**
 * Start Embedding Job
 * Start or resume embedding every un-embedded feedback item in a dataset.
 */
export const startEmbeddingJob = <ThrowOnError extends boolean = false>(
  options: Options<StartEmbeddingJobData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    StartEmbeddingJobResponse,
    StartEmbeddingJobError,
    ThrowOnError
  >({
    url: '/ingestion/datasets/{dataset_id}/embed',
    ...options,
  });
};

/**
 * Start Clustering Run
 * Start a clustering run for a dataset.
 *
 * Args:
 * request: Request body with dataset_id, mode, and optional params.
 *
 * Returns:
 * 202 with the ClusteringRun.
 * 404 if dataset not found.
 * 409 if dataset has no embeddings.
 */
export const startClusteringRun = <ThrowOnError extends boolean = false>(
  options: Options<StartClusteringRunData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    StartClusteringRunResponse,
    StartClusteringRunError,
    ThrowOnError
  >({
    url: '/clusters/runs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Clustering Run
 * Fetch a clustering run by ID.
 */
export const getClusteringRun = <ThrowOnError extends boolean = false>(
  options: Options<GetClusteringRunData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetClusteringRunResponse,
    GetClusteringRunError,
    ThrowOnError
  >({
    url: '/clusters/runs/{run_id}',
    ...options,
  });
};

/**
 * List Clusters
 * List clusters from the current run for a dataset, ordered by size descending.
 */
export const listClusters = <ThrowOnError extends boolean = false>(
  options: Options<ListClustersData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListClustersResponse,
    ListClustersError,
    ThrowOnError
  >({
    url: '/clusters',
    ...options,
  });
};

/**
 * List Cluster Items
 * List feedback items in a cluster, paginated.
 */
export const listClusterItems = <ThrowOnError extends boolean = false>(
  options: Options<ListClusterItemsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListClusterItemsResponse,
    ListClusterItemsError,
    ThrowOnError
  >({
    url: '/clusters/{cluster_id}/items',
    ...options,
  });
};

/**
 * Get Cluster Summary
 * Get or generate a Claude summary for a cluster.
 *
 * Returns a cached summary if available and not forced; otherwise generates
 * a new one via Claude (label, summary text, representative quotes) and caches it.
 *
 * Args:
 * cluster_id: Cluster to summarize.
 * force: If true, bypass cache and regenerate.
 * db: Database session.
 * settings: Application settings. Injected rather than fetched in-body so
 * `dependency_overrides[get_settings]` actually takes effect in tests.
 *
 * Returns:
 * 200 with ClusterSummaryResponse (cluster_id, label, summary, quotes, cached_at).
 * 404 if cluster not found.
 * 503 if summarization failed (Claude API error or validation failure).
 */
export const getClusterSummary = <ThrowOnError extends boolean = false>(
  options: Options<GetClusterSummaryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetClusterSummaryResponse,
    GetClusterSummaryError,
    ThrowOnError
  >({
    url: '/clusters/{cluster_id}/summary',
    ...options,
  });
};

/**
 * Get Cluster Map
 * Get the cluster map for visualization — all points + cluster metadata.
 */
export const getClusterMap = <ThrowOnError extends boolean = false>(
  options: Options<GetClusterMapData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetClusterMapResponse,
    GetClusterMapError,
    ThrowOnError
  >({
    url: '/clusters/map',
    ...options,
  });
};

/**
 * Post Chat Message
 * Answer a question over the feedback corpus, streaming the answer as SSE.
 *
 * Emits ``token*`` → ``citations`` → ``done``; on failure a single ``error``
 * frame and nothing after it. Note the stream also carries periodic ``:``
 * keepalive comments, which clients must skip.
 *
 * A sync generator on purpose: the body blocks on the Anthropic HTTP stream
 * and on SQLAlchemy, so FastAPI runs it in a threadpool rather than on the
 * event loop.
 *
 * Returns:
 * 200 with an SSE stream.
 * 404 if the dataset or conversation does not exist.
 * 503 if a Claude call is required but no API key is configured.
 */
export const postChatMessage = <ThrowOnError extends boolean = false>(
  options: Options<PostChatMessageData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<unknown, PostChatMessageError, ThrowOnError>({
    url: '/chat/messages',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Conversation
 * Replay a conversation and its messages, ordered by ``sequence``.
 *
 * Returns:
 * 200 with the conversation and its messages.
 * 404 if the conversation does not exist.
 */
export const getConversation = <ThrowOnError extends boolean = false>(
  options: Options<GetConversationData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetConversationResponse,
    GetConversationError,
    ThrowOnError
  >({
    url: '/chat/conversations/{conversation_id}',
    ...options,
  });
};
