// This file is auto-generated by @hey-api/openapi-ts

export type BodyUploadCsv = {
  file: string;
};

/**
 * Dataset metadata plus every feedback item ingested from it.
 */
export type DatasetDetail = {
  id: string;
  filename: string;
  status: DatasetStatus;
  row_count_total: number;
  row_count_accepted: number;
  row_count_rejected: number;
  created_at: string;
  feedback_items?: Array<FeedbackItemOut>;
};

/**
 * Lifecycle of an ingested dataset as it moves through the pipeline.
 */
export type DatasetStatus = 'ingested' | 'embedded' | 'clustered' | 'summarized';

/**
 * Dataset-level metadata, without its feedback items.
 */
export type DatasetSummary = {
  id: string;
  filename: string;
  status: DatasetStatus;
  row_count_total: number;
  row_count_accepted: number;
  row_count_rejected: number;
  created_at: string;
};

/**
 * A single persisted feedback row, as returned by the API.
 */
export type FeedbackItemOut = {
  id: string;
  feedback_text: string;
  submitted_at: string | null;
  source: string | null;
  customer_id: string | null;
  row_number: number;
};

export type HttpValidationError = {
  detail?: Array<ValidationError>;
};

/**
 * One rejected CSV row, reported back to the caller.
 */
export type IngestionError = {
  row_number: number;
  column?: string | null;
  reason: string;
};

/**
 * Result of a CSV upload — accepted/rejected counts and per-row reasons.
 *
 * ``dataset_id`` is ``None`` when nothing was persisted (zero valid rows).
 * ``errors`` is capped at ``settings.max_reported_errors``; ``rows_rejected``
 * always reports the true total regardless of the cap.
 */
export type IngestionReport = {
  dataset_id?: string | null;
  filename: string;
  rows_total: number;
  rows_accepted: number;
  rows_rejected: number;
  errors?: Array<IngestionError>;
  errors_truncated?: boolean;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: {
    [key: string]: unknown;
  };
};

export type HealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthResponses = {
  /**
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type UploadCsvData = {
  body: BodyUploadCsv;
  path?: never;
  query?: never;
  url: '/ingestion/uploads';
};

export type UploadCsvErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadCsvError = UploadCsvErrors[keyof UploadCsvErrors];

export type UploadCsvResponses = {
  /**
   * Successful Response
   */
  201: IngestionReport;
};

export type UploadCsvResponse = UploadCsvResponses[keyof UploadCsvResponses];

export type ListDatasetsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/ingestion/datasets';
};

export type ListDatasetsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListDatasetsError = ListDatasetsErrors[keyof ListDatasetsErrors];

export type ListDatasetsResponses = {
  /**
   * Successful Response
   */
  200: Array<DatasetSummary>;
};

export type ListDatasetsResponse = ListDatasetsResponses[keyof ListDatasetsResponses];

export type GetDatasetData = {
  body?: never;
  path: {
    dataset_id: string;
  };
  query?: never;
  url: '/ingestion/datasets/{dataset_id}';
};

export type GetDatasetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetDatasetError = GetDatasetErrors[keyof GetDatasetErrors];

export type GetDatasetResponses = {
  /**
   * Successful Response
   */
  200: DatasetDetail;
};

export type GetDatasetResponse = GetDatasetResponses[keyof GetDatasetResponses];

export type ClientOptions = {
  baseUrl: 'http://localhost:8000' | (string & {});
};
