// This file is auto-generated by @hey-api/openapi-ts

export type BodyUploadCsv = {
  file: string;
};

/**
 * One point in the cluster visualization map.
 */
export type ClusterAssignmentPoint = {
  feedback_item_id: string;
  cluster_id: string | null;
  x: number;
  y: number;
};

/**
 * Flat payload for cluster visualization — all points + cluster metadata.
 */
export type ClusterMap = {
  points: Array<ClusterAssignmentPoint>;
  clusters: Array<ClusterSummary>;
};

/**
 * Lightweight cluster info (for listing).
 */
export type ClusterSummary = {
  id: string;
  cluster_index: number;
  item_count: number;
  label: string | null;
};

/**
 * A clustering run — maps feedback items to semantic clusters.
 */
export type ClusteringRun = {
  id: string;
  dataset_id: string;
  algorithm: string;
  params: {
    [key: string]: unknown;
  };
  random_seed: number;
  cluster_count: number;
  noise_count: number;
  is_current: boolean;
  created_at: string;
};

/**
 * Request body for POST /clusters/runs.
 */
export type ClusteringRunRequest = {
  dataset_id: string;
  mode?: string;
  params?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Dataset metadata plus every feedback item ingested from it.
 */
export type DatasetDetail = {
  id: string;
  filename: string;
  status: DatasetStatus;
  row_count_total: number;
  row_count_accepted: number;
  row_count_rejected: number;
  created_at: string;
  feedback_items?: Array<FeedbackItemOut>;
};

/**
 * Lifecycle of an ingested dataset as it moves through the pipeline.
 */
export type DatasetStatus = 'ingested' | 'embedded' | 'clustered' | 'summarized';

/**
 * Dataset-level metadata, without its feedback items.
 */
export type DatasetSummary = {
  id: string;
  filename: string;
  status: DatasetStatus;
  row_count_total: number;
  row_count_accepted: number;
  row_count_rejected: number;
  created_at: string;
};

/**
 * Lifecycle of one embedding run for a dataset.
 */
export type EmbeddingJobState = 'pending' | 'running' | 'completed' | 'failed';

/**
 * The latest embedding run's state for a dataset.
 */
export type EmbeddingJobStatus = {
  dataset_id: string;
  state: EmbeddingJobState;
  items_total: number;
  items_embedded: number;
  items_failed: number;
  model: string;
  dimension: number;
  error: string | null;
  started_at: string | null;
  finished_at: string | null;
};

/**
 * A single persisted feedback row, as returned by the API.
 */
export type FeedbackItemOut = {
  id: string;
  feedback_text: string;
  submitted_at: string | null;
  source: string | null;
  customer_id: string | null;
  row_number: number;
};

export type HttpValidationError = {
  detail?: Array<ValidationError>;
};

/**
 * One rejected CSV row, reported back to the caller.
 */
export type IngestionError = {
  row_number: number;
  column?: string | null;
  reason: string;
};

/**
 * Result of a CSV upload — accepted/rejected counts and per-row reasons.
 *
 * ``dataset_id`` is ``None`` when nothing was persisted (zero valid rows).
 * ``errors`` is capped at ``settings.max_reported_errors``; ``rows_rejected``
 * always reports the true total regardless of the cap.
 */
export type IngestionReport = {
  dataset_id?: string | null;
  filename: string;
  rows_total: number;
  rows_accepted: number;
  rows_rejected: number;
  errors?: Array<IngestionError>;
  errors_truncated?: boolean;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: {
    [key: string]: unknown;
  };
};

export type HealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthResponses = {
  /**
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type UploadCsvData = {
  body: BodyUploadCsv;
  path?: never;
  query?: never;
  url: '/ingestion/uploads';
};

export type UploadCsvErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadCsvError = UploadCsvErrors[keyof UploadCsvErrors];

export type UploadCsvResponses = {
  /**
   * Successful Response
   */
  201: IngestionReport;
};

export type UploadCsvResponse = UploadCsvResponses[keyof UploadCsvResponses];

export type ListDatasetsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/ingestion/datasets';
};

export type ListDatasetsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListDatasetsError = ListDatasetsErrors[keyof ListDatasetsErrors];

export type ListDatasetsResponses = {
  /**
   * Successful Response
   */
  200: Array<DatasetSummary>;
};

export type ListDatasetsResponse = ListDatasetsResponses[keyof ListDatasetsResponses];

export type GetDatasetData = {
  body?: never;
  path: {
    dataset_id: string;
  };
  query?: never;
  url: '/ingestion/datasets/{dataset_id}';
};

export type GetDatasetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetDatasetError = GetDatasetErrors[keyof GetDatasetErrors];

export type GetDatasetResponses = {
  /**
   * Successful Response
   */
  200: DatasetDetail;
};

export type GetDatasetResponse = GetDatasetResponses[keyof GetDatasetResponses];

export type GetEmbeddingJobData = {
  body?: never;
  path: {
    dataset_id: string;
  };
  query?: never;
  url: '/ingestion/datasets/{dataset_id}/embed';
};

export type GetEmbeddingJobErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetEmbeddingJobError = GetEmbeddingJobErrors[keyof GetEmbeddingJobErrors];

export type GetEmbeddingJobResponses = {
  /**
   * Successful Response
   */
  200: EmbeddingJobStatus;
};

export type GetEmbeddingJobResponse = GetEmbeddingJobResponses[keyof GetEmbeddingJobResponses];

export type StartEmbeddingJobData = {
  body?: never;
  path: {
    dataset_id: string;
  };
  query?: never;
  url: '/ingestion/datasets/{dataset_id}/embed';
};

export type StartEmbeddingJobErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StartEmbeddingJobError = StartEmbeddingJobErrors[keyof StartEmbeddingJobErrors];

export type StartEmbeddingJobResponses = {
  /**
   * Successful Response
   */
  202: EmbeddingJobStatus;
};

export type StartEmbeddingJobResponse =
  StartEmbeddingJobResponses[keyof StartEmbeddingJobResponses];

export type StartClusteringRunData = {
  body: ClusteringRunRequest;
  path?: never;
  query?: never;
  url: '/clusters/runs';
};

export type StartClusteringRunErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StartClusteringRunError = StartClusteringRunErrors[keyof StartClusteringRunErrors];

export type StartClusteringRunResponses = {
  /**
   * Successful Response
   */
  202: ClusteringRun;
};

export type StartClusteringRunResponse =
  StartClusteringRunResponses[keyof StartClusteringRunResponses];

export type GetClusteringRunData = {
  body?: never;
  path: {
    run_id: string;
  };
  query?: never;
  url: '/clusters/runs/{run_id}';
};

export type GetClusteringRunErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetClusteringRunError = GetClusteringRunErrors[keyof GetClusteringRunErrors];

export type GetClusteringRunResponses = {
  /**
   * Successful Response
   */
  200: ClusteringRun;
};

export type GetClusteringRunResponse = GetClusteringRunResponses[keyof GetClusteringRunResponses];

export type ListClustersData = {
  body?: never;
  path?: never;
  query: {
    dataset_id: string;
  };
  url: '/clusters';
};

export type ListClustersErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListClustersError = ListClustersErrors[keyof ListClustersErrors];

export type ListClustersResponses = {
  /**
   * Successful Response
   */
  200: Array<ClusterSummary>;
};

export type ListClustersResponse = ListClustersResponses[keyof ListClustersResponses];

export type ListClusterItemsData = {
  body?: never;
  path: {
    cluster_id: string;
  };
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/clusters/{cluster_id}/items';
};

export type ListClusterItemsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListClusterItemsError = ListClusterItemsErrors[keyof ListClusterItemsErrors];

export type ListClusterItemsResponses = {
  /**
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type ListClusterItemsResponse = ListClusterItemsResponses[keyof ListClusterItemsResponses];

export type GetClusterMapData = {
  body?: never;
  path?: never;
  query: {
    dataset_id: string;
  };
  url: '/clusters/map';
};

export type GetClusterMapErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetClusterMapError = GetClusterMapErrors[keyof GetClusterMapErrors];

export type GetClusterMapResponses = {
  /**
   * Successful Response
   */
  200: ClusterMap;
};

export type GetClusterMapResponse = GetClusterMapResponses[keyof GetClusterMapResponses];

export type ClientOptions = {
  baseUrl: 'http://localhost:8000' | (string & {});
};
