// This file is auto-generated by @hey-api/openapi-ts

export type HealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthResponses = {
  /**
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type ClientOptions = {
  baseUrl: 'http://localhost:8000' | (string & {});
};
