"""add clustering

Revision ID: 2da5ea9650a0
Revises: 8ba414c913f8
Create Date: 2026-08-26 09:55:18.576093

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2da5ea9650a0'
down_revision: str | None = '8ba414c913f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clustering_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('cluster_count', sa.Integer(), nullable=False),
    sa.Column('noise_count', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clustering_runs_dataset_id'), 'clustering_runs', ['dataset_id'], unique=False)  # noqa: E501
    op.create_index(op.f('ix_clustering_runs_is_current'), 'clustering_runs', ['is_current'], unique=False)  # noqa: E501
    op.create_table('clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_index', sa.Integer(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['clustering_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_run_id'), 'clusters', ['run_id'], unique=False)
    op.create_table('cluster_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_item_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_item_id'], ['feedback_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['clustering_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_assignments_cluster_id'), 'cluster_assignments', ['cluster_id'], unique=False)  # noqa: E501
    op.create_index(op.f('ix_cluster_assignments_feedback_item_id'), 'cluster_assignments', ['feedback_item_id'], unique=False)  # noqa: E501
    op.create_index(op.f('ix_cluster_assignments_run_id'), 'cluster_assignments', ['run_id'], unique=False)  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_assignments_run_id'), table_name='cluster_assignments')
    op.drop_index(op.f('ix_cluster_assignments_feedback_item_id'), table_name='cluster_assignments')
    op.drop_index(op.f('ix_cluster_assignments_cluster_id'), table_name='cluster_assignments')
    op.drop_table('cluster_assignments')
    op.drop_index(op.f('ix_clusters_run_id'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_clustering_runs_is_current'), table_name='clustering_runs')
    op.drop_index(op.f('ix_clustering_runs_dataset_id'), table_name='clustering_runs')
    op.drop_table('clustering_runs')
    # ### end Alembic commands ###
