"""add unique constraint cluster_assignments

Revision ID: 57b7a3936ceb
Revises: 2da5ea9650a0
Create Date: 2026-08-26 10:55:28.156080

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '57b7a3936ceb'
down_revision: str | None = '2da5ea9650a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # SQLite cannot ALTER a constraint onto an existing table, so this needs
    # batch mode's copy-and-move strategy. The autogenerated
    # `op.create_unique_constraint` this replaced raised NotImplementedError,
    # which broke `alembic upgrade head` for every revision after this one.
    with op.batch_alter_table('cluster_assignments') as batch_op:
        batch_op.create_unique_constraint(
            'uq_cluster_assignments_run_item', ['run_id', 'feedback_item_id']
        )


def downgrade() -> None:
    with op.batch_alter_table('cluster_assignments') as batch_op:
        batch_op.drop_constraint('uq_cluster_assignments_run_item', type_='unique')
