"""add unique constraint cluster_assignments

Revision ID: 57b7a3936ceb
Revises: 2da5ea9650a0
Create Date: 2026-08-26 10:55:28.156080

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '57b7a3936ceb'
down_revision: str | None = '2da5ea9650a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cluster_assignments_run_item', 'cluster_assignments', ['run_id', 'feedback_item_id'])  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cluster_assignments_run_item', 'cluster_assignments', type_='unique')
    # ### end Alembic commands ###
