"""add embeddings

Revision ID: 8ba414c913f8
Revises: 6b16ce9ba665
Create Date: 2026-08-20 09:33:00.406442

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8ba414c913f8'
down_revision: str | None = '6b16ce9ba665'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column(
        'state',
        sa.Enum(
            'pending', 'running', 'completed', 'failed',
            name='embeddingjobstate', native_enum=False,
        ),
        nullable=False,
    ),
    sa.Column('items_total', sa.Integer(), nullable=False),
    sa.Column('items_embedded', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id')
    )
    op.add_column('feedback_items', sa.Column('embedding', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_items', 'embedding')
    op.drop_table('embedding_jobs')
    # ### end Alembic commands ###
